# SITE CONFIGURATION
baseurl: ""
url: "https://randmusings.github.io/"

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: rand() musings
  avatar: assets/img/avatar.png
  favicon: assets/favicon.ico
  gravatar: # Email MD5 hash
  description: "A geek's eclectic contemplations" # used by search engines

  # Header and footer text
  header_text: >
    <p>
      Hello! I'm Divay Prakash and welcome to my blog <a href="https://randmusings.github.io/">rand() musings</a>.
    </p>
    <p>
      This is just an outlet for a stream of random and sometimes not-so-random thoughts so please bear with me.
      And if you find it fun, then do stick around for more! You can check out my latest posts below.
    </p>
  header_text_feature_image:
  footer_text: >
    <p>Made with ðŸ’™ by <a href="https://divayprakash.github.io/">Divay Prakash</a></p>

  # Icons
  rss: true
  website: https://divayprakash.github.io/
  email_address: divayprakash0@gmail.com
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  gitlab:
  github: divayprakash
  gitter:
  google_plus:
  instagram:
  linkedin:  https://www.linkedin.com/in/divayprakash/
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter: divayprakash3
  wordpress:
  youtube:

  # Scripts
  google_analytics: # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname:
  katex: true # Enable if using math markup
  search: true # Enable the search feature

  # Localization strings
  str_follow_on: "Follow me on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next_post: "Next post"
  str_previous_post: "Previous post"
  str_next_page: "Next"
  str_previous_page: "Prev"
  str_continue_reading: "Continue reading"
  str_javascript_required_disqus: "Please enable JavaScript to view comments."
  str_search_no_results: "No results found"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  # Post navigation
  post_navigation: true

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
plugins: [jekyll-paginate, jemoji, jekyll-avatar]
exclude:
  - Gemfile
  - Gemfile.lock
